# Copyright 2020 Darius Neatu <neatudarius@gmail.com>

CC = gcc
CFLAGS = -Wall -Wextra -g

# List of source files
SRC = main.c image_utils.c marching_squares.c

# List of object files (generated by replacing .c with .o for each source file)
OBJ = $(SRC:.c=.o)

EXEC = marching_squares

all: build

build: $(EXEC)

# Rule to create the executable by linking object files
$(EXEC): $(OBJ)
	$(CC) $(OBJ) -o $(EXEC)

# Rule to compile .c files into .o files
%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

# Clean rule to remove compiled files
clean:
	rm -f $(OBJ) $(EXEC)

pack:
	zip -FSr 313CA_TraistaruDragosAndrei_Tema2.zip README Makefile *.c *.h

# Phony targets (to avoid conflicts with files named "all", "build", or "clean")
.PHONY: all build clean rebuild

